ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 4.10.2018 16:59:15
user User
END
objects 143      
END

[% zCMaterial 39939 0]
	name=string:NW_MISC_LIGHTDECAL_03
	matGroup=enum:0
	color=color:24 24 24 255
	smoothAngle=float:60
	texture=string:NW_MISC_LIGHTDECAL_03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:9.9999997e-006 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:1
	alphaFunc=enum:3
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 1]
	name=string:NW_SEQ_GRASSPATH_01_XL
	matGroup=enum:4
	color=color:103 88 65 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GRASSPATH_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 2]
	name=string:NW_SEQ_GRASSPATH_END_01_XL
	matGroup=enum:4
	color=color:96 82 55 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GRASSPATH_END_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 3]
	name=string:NW_SEQ_GROUND_02_XL
	matGroup=enum:4
	color=color:86 76 43 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GROUND_02_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 4]
	name=string:NW_SEQ_MAYA_GROUND_RED_01_L
	matGroup=enum:2
	color=color:102 90 70 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_RED_01_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 5]
	name=string:NW_SEQ_MAYA_GROUND_TRANS_01_XL
	matGroup=enum:4
	color=color:102 88 62 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_TRANS_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 6]
	name=string:NW_SEQ_MAYA_GROUND_TRANS_02_XL
	matGroup=enum:4
	color=color:105 84 59 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_TRANS_02_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 7]
	name=string:NW_SEQ_MAYA_NATURESTONE_03_XL
	matGroup=enum:2
	color=color:106 76 61 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_NATURESTONE_03_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 8]
	name=string:NW_SEQ_MAYA_NATURESTONE_04_XL
	matGroup=enum:2
	color=color:104 94 67 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_NATURESTONE_04_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 9]
	name=string:NW_SEQ_MAYA_ORNAMENT_GREEN_02_L
	matGroup=enum:2
	color=color:51 51 33 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_GREEN_02_L.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 10]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_01
	matGroup=enum:2
	color=color:106 89 65 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 11]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_02
	matGroup=enum:2
	color=color:96 83 63 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_02.TGA
	texScale=string:512 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 12]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_03
	matGroup=enum:2
	color=color:88 72 60 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 13]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_05
	matGroup=enum:2
	color=color:116 98 74 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_05.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 14]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_06_L
	matGroup=enum:2
	color=color:93 81 62 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_06_L.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 15]
	name=string:NW_SEQ_MAYA_STONE_TRANS_02_XL
	matGroup=enum:2
	color=color:89 74 54 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONE_TRANS_02_XL.TGA
	texScale=string:1024 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 16]
	name=string:NW_SEQ_MAYA_WALL_09
	matGroup=enum:2
	color=color:124 107 83 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_09.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 17]
	name=string:NW_SEQ_MAYA_WALL_10
	matGroup=enum:2
	color=color:90 76 58 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_10.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 18]
	name=string:NW_SEQ_MAYA_WALL_11
	matGroup=enum:2
	color=color:137 118 91 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_11.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 19]
	name=string:NW_SEQ_MAYA_WALL_12
	matGroup=enum:2
	color=color:72 67 62 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_12.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 20]
	name=string:NW_SEQ_MAYA_WALL_RED_01_XL
	matGroup=enum:2
	color=color:110 92 75 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_RED_01_XL.TGA
	texScale=string:1024 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 21]
	name=string:NW_SEQ_MAYA_WALL_RED_04
	matGroup=enum:2
	color=color:107 97 74 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_RED_04.TGA
	texScale=string:1024 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 22]
	name=string:NW_MISC_SWAMPWATER_01
	matGroup=enum:5
	color=color:33 49 40 150
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.5
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 23]
	name=string:NW_SEQ_GROUND_01_XL
	matGroup=enum:4
	color=color:106 92 76 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GROUND_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 24]
	name=string:NW_SEQ_MAYA_GROUND_TRANS_04_XL
	matGroup=enum:4
	color=color:105 89 63 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_TRANS_04_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 25]
	name=string:NW_SEQ_MAYA_WALL_14
	matGroup=enum:2
	color=color:86 78 66 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_14.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 26]
	name=string:NW_SEQ_MAYA_WALL_15
	matGroup=enum:2
	color=color:69 61 48 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_15.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 27]
	name=string:NW_SEQ_MISC_BAMBUS_01_XL
	matGroup=enum:3
	color=color:92 82 61 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_BAMBUS_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 28]
	name=string:NW_SEQ_MISC_STRAWHUT_01
	matGroup=enum:0
	color=color:49 41 26 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_STRAWHUT_01.TGA
	texScale=string:512 128
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 29]
	name=string:NW_SEQ_MISC_STRAWROOF_01
	matGroup=enum:4
	color=color:92 77 51 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_STRAWROOF_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 30]
	name=string:NW_SEQ_MISC_WALL_01
	matGroup=enum:2
	color=color:97 88 63 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_WALL_01.TGA
	texScale=string:1024 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 31]
	name=string:NW_SEQ_MISC_WOOD_01
	matGroup=enum:3
	color=color:88 75 58 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_WOOD_01.TGA
	texScale=string:128 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 32]
	name=string:NW_SEQ_NATURE_PALM_01
	matGroup=enum:0
	color=color:38 41 26 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALM_01.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 33]
	name=string:NW_SEQ_NATURE_PALM_02
	matGroup=enum:0
	color=color:30 17 11 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALM_02.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 34]
	name=string:NW_SEQ_NATURE_PALMBARK_01
	matGroup=enum:3
	color=color:125 102 64 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALMBARK_01.TGA
	texScale=string:256 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 35]
	name=string:NW_SEQ_NATURE_PALMBARK_02
	matGroup=enum:3
	color=color:101 84 68 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALMBARK_02.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 36]
	name=string:NW_SEQ_NATURE_WHITESAND_01
	matGroup=enum:4
	color=color:195 178 158 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WHITESAND_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 37]
	name=string:NW_SEQ_NATURE_WHITESAND_02
	matGroup=enum:4
	color=color:143 127 106 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WHITESAND_02.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 38]
	name=string:NW_SEQ_NATURE_WHITESAND_TRANS_01
	matGroup=enum:4
	color=color:166 150 129 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WHITESAND_TRANS_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 39]
	name=string:NW_SEQ_NATURE_WHITESAND_TRANS_02
	matGroup=enum:4
	color=color:157 142 116 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WHITESAND_TRANS_02.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 40]
	name=string:NW_MISC_CAVEWALL_03
	matGroup=enum:2
	color=color:50 48 31 255
	smoothAngle=float:60
	texture=string:NW_MISC_CAVEWALL_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 41]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_04
	matGroup=enum:2
	color=color:112 97 75 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_04.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 42]
	name=string:NW_SEQ_MAYA_WALL_GREEN_05
	matGroup=enum:2
	color=color:47 50 22 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_05.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 43]
	name=string:NW_SEQ_MAYA_WALL_GREEN_10
	matGroup=enum:2
	color=color:43 42 26 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_10.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 44]
	name=string:NW_SEQ_MAYA_WALL_GREEN_11
	matGroup=enum:2
	color=color:44 46 26 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_11.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 45]
	name=string:NW_SEQ_MAYA_WALL_GREEN_15
	matGroup=enum:2
	color=color:69 76 53 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_15.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 46]
	name=string:NW_SEQ_MAYA_WALL_PICTURE_01
	matGroup=enum:2
	color=color:50 38 20 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_PICTURE_01.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 47]
	name=string:NW_SEQ_MAYA_WALLMESSAGE_01
	matGroup=enum:2
	color=color:51 54 39 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALLMESSAGE_01.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 48]
	name=string:NW_CITY_BROKENSTONE_01
	matGroup=enum:2
	color=color:94 78 50 255
	smoothAngle=float:60
	texture=string:NW_CITY_BROKENSTONE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 49]
	name=string:NW_SEQ_MAYA_ORNAMENT_GREEN_05
	matGroup=enum:2
	color=color:116 98 74 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_05.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 50]
	name=string:NW_SEQ_MAYA_STONE_TRANS_01_XL
	matGroup=enum:2
	color=color:105 85 64 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONE_TRANS_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 51]
	name=string:NW_SEQ_MOUNTAIN_03_XL
	matGroup=enum:2
	color=color:87 78 46 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MOUNTAIN_03_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 52]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_06_XL
	matGroup=enum:4
	color=color:71 62 32 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_06_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 53]
	name=string:NW_SEQ_NATURE_SWAMPGROUND_01_XL
	matGroup=enum:4
	color=color:60 50 26 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_SWAMPGROUND_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 54]
	name=string:NW_SEQ_NATURE_TREEBARK_01
	matGroup=enum:3
	color=color:93 84 57 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_TREEBARK_01.TGA
	texScale=string:256 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 55]
	name=string:NW_SEQ_NATURE_WALLTRANS_03_XL
	matGroup=enum:2
	color=color:94 83 54 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WALLTRANS_03_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 56]
	name=string:NW_SEQ_GROUND_04_XL
	matGroup=enum:4
	color=color:128 109 98 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GROUND_04_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 57]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_05_XL
	matGroup=enum:4
	color=color:112 97 74 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_05_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 58]
	name=string:NW_SEQ_MOUNTAIN_02_XL
	matGroup=enum:2
	color=color:61 65 41 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MOUNTAIN_02_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 59]
	name=string:NW_SEQ_MAYA_GROUND_RED_01_XL
	matGroup=enum:2
	color=color:102 90 70 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_RED_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 60]
	name=string:NW_SEQ_MAYA_STONEBROKEN_02
	matGroup=enum:2
	color=color:89 76 52 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONEBROKEN_02.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 61]
	name=string:NW_SEQ_MISC_BAMBOO_01
	matGroup=enum:3
	color=color:169 142 91 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MISC_BAMBOO_01.TGA
	texScale=string:64 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 62]
	name=string:NW_CITY_WOOD_02
	matGroup=enum:3
	color=color:88 84 67 255
	smoothAngle=float:60
	texture=string:NW_CITY_WOOD_02.TGA
	texScale=string:1024 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 63]
	name=string:NW_SEQ_CANYONWALL_01
	matGroup=enum:4
	color=color:136 90 50 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_01.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 64]
	name=string:NW_SEQ_CANYONWALL_02
	matGroup=enum:2
	color=color:113 71 42 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_02.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 65]
	name=string:NW_SEQ_CANYONWALL_03
	matGroup=enum:2
	color=color:99 74 45 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_03.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 66]
	name=string:NW_SEQ_CANYONWALL_04
	matGroup=enum:2
	color=color:118 82 48 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_04.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 67]
	name=string:NW_SEQ_CANYONWALL_05
	matGroup=enum:2
	color=color:135 85 46 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_05.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 68]
	name=string:NW_SEQ_CANYONWALL_06
	matGroup=enum:4
	color=color:129 83 45 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_06.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 69]
	name=string:NW_SEQ_CANYONWALL_07
	matGroup=enum:4
	color=color:124 81 44 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_07.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 70]
	name=string:NW_SEQ_CANYONWALL_08
	matGroup=enum:4
	color=color:132 83 43 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_08.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 71]
	name=string:NW_SEQ_CANYONWALL_09
	matGroup=enum:4
	color=color:149 102 57 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_09.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 72]
	name=string:NW_SEQ_CANYONWALL_10
	matGroup=enum:2
	color=color:109 86 62 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_10.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 73]
	name=string:NW_SEQ_CANYONWALL_11
	matGroup=enum:2
	color=color:127 85 48 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_11.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 74]
	name=string:NW_SEQ_CANYONWALL_TRANS_01
	matGroup=enum:4
	color=color:114 88 55 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_TRANS_01.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 75]
	name=string:NW_NATURE_STONE_01
	matGroup=enum:2
	color=color:107 92 70 255
	smoothAngle=float:60
	texture=string:NW_NATURE_STONE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 76]
	name=string:NW_SEQ_MAYA_GOLDMINE_01_XL
	matGroup=enum:2
	color=color:103 76 56 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GOLDMINE_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 77]
	name=string:NW_SEQ_MAYA_NATURESTONE_02_XL
	matGroup=enum:2
	color=color:86 57 37 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_NATURESTONE_02_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 78]
	name=string:NW_SEQ_MAYA_NATURESTONE_05_L
	matGroup=enum:2
	color=color:78 69 47 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_NATURESTONE_05_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 79]
	name=string:NW_SEQ_MAYA_STONE_TRANS_04_L
	matGroup=enum:2
	color=color:97 81 53 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONE_TRANS_04_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 80]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_07_XL
	matGroup=enum:2
	color=color:115 90 77 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_07_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 81]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_08_L
	matGroup=enum:2
	color=color:115 78 53 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_08_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 82]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_10_L
	matGroup=enum:4
	color=color:112 86 69 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_10_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 83]
	name=string:NW_SEQ_NATURE_GROUNDTRANS_9_L
	matGroup=enum:2
	color=color:106 77 55 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_GROUNDTRANS_9_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 84]
	name=string:NW_HARBOUR_STAIRS_03
	matGroup=enum:2
	color=color:39 35 20 255
	smoothAngle=float:60
	texture=string:NW_HARBOUR_STAIRS_03.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 85]
	name=string:NW_SEQ_CANYONTEMPLE_BORDE_01
	matGroup=enum:2
	color=color:70 57 36 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONTEMPLE_BORDE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 86]
	name=string:NW_SEQ_CANYONTEMPLE_PILLAR_01
	matGroup=enum:2
	color=color:112 90 63 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONTEMPLE_PILLAR_01.TGA
	texScale=string:128 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 87]
	name=string:NW_SEQ_CANYONTEMPLE_PILLAR_02
	matGroup=enum:2
	color=color:71 59 38 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONTEMPLE_PILLAR_02.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 88]
	name=string:NW_SEQ_CANYONTEMPLE_STATUE_01
	matGroup=enum:2
	color=color:95 73 52 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONTEMPLE_STATUE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 89]
	name=string:NW_SEQ_GRAVELPATH_01
	matGroup=enum:4
	color=color:118 98 83 255
	smoothAngle=float:60
	texture=string:NW_SEQ_GRAVELPATH_01.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 90]
	name=string:NW_SEQ_MAYA_STONEBROKEN_03
	matGroup=enum:2
	color=color:67 66 42 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONEBROKEN_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 91]
	name=string:NW_SEQ_MAYA_WALL_04
	matGroup=enum:2
	color=color:84 70 48 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_04.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 92]
	name=string:NW_SEQ_NATURE_WALL_TRANS_04_XL
	matGroup=enum:2
	color=color:83 73 41 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_WALL_TRANS_04_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 93]
	name=string:DNW_CITY_WOOD_02
	matGroup=enum:3
	color=color:88 84 67 255
	smoothAngle=float:60
	texture=string:NW_CITY_WOOD_02.TGA
	texScale=string:1024 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 94]
	name=string:NW_SEQ_MAYA_STONE_TRANS_04_XL
	matGroup=enum:2
	color=color:96 80 52 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_STONE_TRANS_04_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 95]
	name=string:NW_SEQ_NATURE_PALMBARK_011
	matGroup=enum:3
	color=color:125 102 64 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALMBARK_01.TGA
	texScale=string:256 2048
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 96]
	name=string:NW_DRAGONISLAND_ALCHEMY_RED_SHRINE_01
	matGroup=enum:2
	color=color:34 15 12 255
	smoothAngle=float:60
	texture=string:NW_DRAGONISLAND_ALCHEMY_RED_SHRINE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 97]
	name=string:NW_SEQ_MAYA_GROUND_GREEN_01_XL
	matGroup=enum:2
	color=color:45 45 25 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_GROUND_GREEN_01_XL.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 98]
	name=string:NW_SEQ_MAYA_NATURESTONE_06_L
	matGroup=enum:2
	color=color:108 91 74 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_NATURESTONE_06_L.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 99]
	name=string:NW_SEQ_MAYA_WALL_03
	matGroup=enum:2
	color=color:72 60 43 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 100]
	name=string:NW_SEQ_MAYA_WALL_06
	matGroup=enum:2
	color=color:101 86 62 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_06.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 101]
	name=string:NW_SEQ_MAYA_WALL_GREEN_06
	matGroup=enum:2
	color=color:51 56 27 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_06.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 102]
	name=string:NW_SEQ_MAYA_WALL_GREEN_14
	matGroup=enum:2
	color=color:45 44 24 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_WALL_GREEN_14.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 103]
	name=string:OTFLSPIKEHOLES_TILE
	matGroup=enum:1
	color=color:36 22 15 255
	smoothAngle=float:60
	texture=string:OTFLSPIKEHOLES_TILE.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 104]
	name=string:STONIE
	matGroup=enum:2
	color=color:107 84 53 255
	smoothAngle=float:60
	texture=string:STEINWAECHTER.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 105]
	name=string:NW_SEQ_CANYONWALL_12
	matGroup=enum:2
	color=color:134 99 56 255
	smoothAngle=float:60
	texture=string:NW_SEQ_CANYONWALL_12.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 106]
	name=string:NW_SEQ_MAYA_ORNAMENT_RED_06
	matGroup=enum:2
	color=color:74 59 44 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_ORNAMENT_RED_06.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 107]
	name=string:NW_SEQ_STATUE_STONEKEEPER_01
	matGroup=enum:2
	color=color:91 75 59 255
	smoothAngle=float:60
	texture=string:NW_SEQ_STATUE_STONEKEEPER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 108]
	name=string:NW_SEQ_NATURE_BARK_01
	matGroup=enum:3
	color=color:117 85 54 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_BARK_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 109]
	name=string:NW_SEQ_NATURE_CANYONBUSH_01
	matGroup=enum:0
	color=color:17 18 8 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_CANYONBUSH_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 110]
	name=string:NW_SEQ_NATURE_CANYONBUSH_02
	matGroup=enum:0
	color=color:11 19 8 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_CANYONBUSH_02.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 111]
	name=string:NW_SEQ_NATURE_CANYONTREE_01
	matGroup=enum:0
	color=color:13 11 10 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_CANYONTREE_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 112]
	name=string:NW_SEQ_NATURE_CANYONTREEBARK_01
	matGroup=enum:3
	color=color:100 94 79 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_CANYONTREEBARK_01.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 113]
	name=string:NW_SEQ_NATURE_CRYSTAL_01
	matGroup=enum:2
	color=color:144 167 140 255
	smoothAngle=float:0
	texture=string:NW_SEQ_NATURE_CRYSTAL_01.TGA
	texScale=string:128 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:1
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 114]
	name=string:NW_SEQ_NATURE_CRYSTAL_02
	matGroup=enum:2
	color=color:156 178 156 255
	smoothAngle=float:0
	texture=string:NW_SEQ_NATURE_CRYSTAL_02.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:1
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 115]
	name=string:NW_SEQ_NATURE_CRYSTAL_ROSE_01
	matGroup=enum:2
	color=color:167 158 140 255
	smoothAngle=float:0
	texture=string:NW_SEQ_NATURE_CRYSTAL_ROSE_01.TGA
	texScale=string:128 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:1
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 116]
	name=string:NW_SEQ_NATURE_CRYSTAL_ROSE_02
	matGroup=enum:2
	color=color:177 173 154 255
	smoothAngle=float:0
	texture=string:NW_SEQ_NATURE_CRYSTAL_ROSE_02.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:1
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 117]
	name=string:NW_SEQ_NATURE_LIANA_01
	matGroup=enum:0
	color=color:18 19 3 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_LIANA_01.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 118]
	name=string:NW_SEQ_NATURE_PALM_03
	matGroup=enum:0
	color=color:29 34 10 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PALM_03.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 119]
	name=string:NW_SEQ_NATURE_PINE_01
	matGroup=enum:0
	color=color:18 15 10 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PINE_01.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 120]
	name=string:NW_SEQ_NATURE_PINE_02
	matGroup=enum:0
	color=color:20 18 13 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PINE_02.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 121]
	name=string:NW_SEQ_NATURE_PINE_03
	matGroup=enum:0
	color=color:22 19 16 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PINE_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 122]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_01
	matGroup=enum:0
	color=color:78 71 56 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_01.TGA
	texScale=string:128 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 123]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_02
	matGroup=enum:0
	color=color:48 55 22 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_02.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 124]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_03
	matGroup=enum:0
	color=color:64 77 39 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_03.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 125]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_04
	matGroup=enum:0
	color=color:76 73 39 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_04.TGA
	texScale=string:128 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 126]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_05
	matGroup=enum:0
	color=color:31 42 11 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_05.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 127]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_06
	matGroup=enum:0
	color=color:38 52 13 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_06.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 128]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_07
	matGroup=enum:0
	color=color:18 17 8 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_07.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 129]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_08
	matGroup=enum:0
	color=color:25 16 13 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_08.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 130]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_09
	matGroup=enum:0
	color=color:39 34 24 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_09.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 131]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_10
	matGroup=enum:0
	color=color:26 27 11 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_10.TGA
	texScale=string:256 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 132]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_11
	matGroup=enum:0
	color=color:223 225 212 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_11.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 133]
	name=string:NW_SEQ_NATURE_ROOFLEAVE_13
	matGroup=enum:0
	color=color:19 19 14 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_ROOFLEAVE_13.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 134]
	name=string:NW_SEQ_NATURE_SMALLBUSH_01
	matGroup=enum:0
	color=color:48 45 36 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_SMALLBUSH_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 135]
	name=string:NW_SEQ_NATURE_SMALLPLANT_01
	matGroup=enum:0
	color=color:20 23 11 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_SMALLPLANT_01.TGA
	texScale=string:256 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 136]
	name=string:NW_SEQ_NATURE_TREE_01
	matGroup=enum:3
	color=color:171 171 166 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_TREE_01.TGA
	texScale=string:1024 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 137]
	name=string:NW_SEQ_NATURE_TREE_02
	matGroup=enum:3
	color=color:19 17 14 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_TREE_02.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 138]
	name=string:NW_SEQ_NATURE_TREEBARK_04
	matGroup=enum:3
	color=color:98 91 83 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_TREEBARK_04.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 139]
	name=string:NW_SEQ_NATURE_TREES_01
	matGroup=enum:0
	color=color:13 16 15 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_TREES_01.TGA
	texScale=string:512 256
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 140]
	name=string:NW_SEQ_MAYA_DUNGEONRELIEF_01
	matGroup=enum:2
	color=color:37 36 20 255
	smoothAngle=float:60
	texture=string:NW_SEQ_MAYA_DUNGEONRELIEF_01.TGA
	texScale=string:512 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 141]
	name=string:NW_SEQ_NATURE_PINE_031
	matGroup=enum:0
	color=color:22 19 16 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PINE_03.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 142]
	name=string:NW_SEQ_NATURE_PINE_021
	matGroup=enum:0
	color=color:20 18 13 255
	smoothAngle=float:60
	texture=string:NW_SEQ_NATURE_PINE_02.TGA
	texScale=string:1024 1024
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:1
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:1
	forceOccluder=bool:0
	environmentalMapping=bool:0
	environmentalMappingStrength=float:1
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:1
	defaultMapping=rawFloat:2.34375 2.34375 
[]
